### PR TITLE
Sort objectives

### LINKED ISSUE #25: Sort objectives
**Is your feature request related to a problem? Please describe.**
During community actions/objective management the order of the objectives is inconsistent and keeps changing after every update

**Describe the solution you'd like**
Sort the objectives by creation date, older ones last

**Describe alternatives you've considered**
Maybe allowing manual control over the order, maybe?

### PR DESCRIPTION
**Pull request by namoscagnm**
## What issue does this PR close
Closes #25 

## Changes Proposed ( a list of new changes introduced by this PR)
Lists objectives in ascending other

### CODE REVIEW

**Comment by zacck** [comment]
@namoscagnm I think for a new feature like this it would be very beneficial to add unit tests so that we can ensure regression doesn't occur down the line ...

**Comment by lucca65** [comment]
nice @namoscagnm! thanks for the contribution. Please add the unit tests and we can merge this 💪

**Comment by lucca65** [comment]
we can all meet on the support group: https://t.me/Cambiatus_Support

**Comment by lucca65** [comment]
In anyways doing unit tests isn't hard at all @namoscagnm. Elixir's documentation is, as always, incredible. Please take a look: https://hexdocs.pm/ex_unit/ExUnit.html

I'm sure doing this test is possible even without assistance, but please ping us in the group if you need anything

**Comment by lucca65** [comment]
I'll merge this and do the tests in a different PR due to inactivity. Thanks for the contribution anyway @namoscagnm

**Comment by lucca65** [comment]
Just so you know, @namoscagnm the code you sent was not behaving correctly.

here is one of the ways to do it correctly:

```elixir
  def query(Objective, _) do
    Objective
    |> order_by([c], desc: c.created_at)
  end
```

**Pull request merged**
