### PR TITLE
Add monthly digest worker

### LINKED ISSUE #195: Send monthly emails with a digest of the news
# Story

I, as an user of the community
Want to keep in touch with what's happening
To be more active and aware about the community

### Use cases

Given that the community has news enabled and had at least one news in the last 30 days
When it comes the end of each month
Then the system sends a digest with all news on the month

Given that the user has the preference of not receiving digest emails
When it comes the end of each month
Then the system dont send this user anything

### Problem description

After the Implementation of our news Broadcast on #188, we need to keep improving it by adding email digests

### PR DESCRIPTION
**Pull request by flpfar**
## What issue does this PR close
Closes #195 

## Changes Proposed ( a list of new changes introduced by this PR)

- [x] Worker with query to get all news from the last 30 days
- [x] Get only members with monthly digest enabled - _ depends on #199 
- [x] Cron to run every month
- [x] Function to send mail to community members
- [x] Email template
- [x] I18n email
- [x] Images host

## How to test ( a list of instructions on how to test this PR)
N/A

Pair with @adubas

### CODE REVIEW

**Comment by flpfar** [comment]
Some comments:
- Upload email images to our server
- "Unsubscribe" button in footer is redirecting to user profile for now
- We couldn't recreate the input fields in email, so it is not there yet

**Review by lucca65 — APPROVED** [review]

**Comment by flpfar** [comment]
@lucca65
Hey bro! Could you please upload the email images in our server?

https://i.ibb.co/N3xhCRw/Group2.png
https://i.ibb.co/RC7gMc8/linkedin.png
https://i.ibb.co/NrBF7Fv/insta.png
https://i.ibb.co/R3YNyP4/medium.png
https://i.ibb.co/JjTRgw3/twitter.png
https://i.ibb.co/wCgfRM4/cambiatus.png

**Comment by flpfar** [comment]
Sure, bro! Here it is:

https://i.ibb.co/4VfzJQG/cambiatus.png
https://i.ibb.co/Yp94NF6/Group2.png
https://i.ibb.co/ydKXyTY/insta.png
https://i.ibb.co/fqJq9hh/linkedin.png
https://i.ibb.co/9wqVPqJ/medium.png
https://i.ibb.co/G03rd4y/twitter.png

**Comment by lucca65** [comment]
Done bro! in the same order:

- 
- 
- 
- 
- 
-

**Comment by lucca65** [comment]
@flpfar Bro, I've done some changes, minor details, but one of them I think its interesting to use! I've modified language from a string to be a GraphQL enum, so this way there is no need to parse/validate the input, and it gives us a nice typed param. I haven't touched our Postgres too, so it was super simple to implement!

Thanks again for the help on this PR, even after several weeks bro!

🙇

**Pull request merged**
