### PR TITLE
Removed non_null contraint on GraphQl schema for community logo

### LINKED ISSUE #279: Add non-null constraint to community logo
We had a problem with https://github.com/cambiatus/frontend/pull/805, where the GraphQl schema does not accept null values for communities logos, but our SQL database does.

There are tow options:

- A migration should be created to ensure that the database also doesn't accept null values on the community logo field.

OR

- We should accept null values on the GraphQl schema

### PR DESCRIPTION
**Pull request by MatheusBuss**
## What issue does this PR close
Closes #279 

## Changes Proposed ( a list of new changes introduced by this PR)
Remove `non_null` constraint on the GraphQl schema for community logo

### CODE REVIEW

**Review by NeoVier — APPROVED** [review]
🧹

**Review by lucca65 — APPROVED** [review]

**Review by NeoVier — CHANGES_REQUESTED** [review]
We should also change the schema for `CommunityPreview`

**Comment by MatheusBuss** [comment]
Thining about it. Using this approach we will need to review how we will need to update how we render the community logo on rich links and emails. There may be other places where the backend is resposible for serving the image directly to the user.

@NeoVier we should organize to serve the same template image

**Comment by NeoVier** [comment]
@MatheusBuss [we decided on Slack](https://cambiatus.slack.com/archives/CB0UA5SBE/p1660328600240529) to use this image: https://cambiatus-uploads.s3.amazonaws.com/cambiatus-uploads/community_2.png

**Review by NeoVier — APPROVED** [review]

**Review by lucca65 — APPROVED** [review]
✅

**Comment by lucca65** [comment]
hey @MatheusBuss I'm going to merge this!

**Pull request merged**
