### PR TITLE
Fix/product category fixes

### PR DESCRIPTION
**Pull request by lucca65**
## What issue does this PR close
Closes N/A

## Changes Proposed ( a list of new changes introduced by this PR)
- Fixes error that would be raised when we try to delete a category already associated with a product. Now it deletes the association with the product.

## How to test ( a list of instructions on how to test this PR)
run `mix test` there are test cases for those bugs

### CODE REVIEW

**Comment by NeoVier** [comment]
@lucca65 já resolvemos isso? https://cambiatus.slack.com/archives/CA83HJAAD/p1660764053454079?thread_ts=1660648202.151329&cid=CA83HJAAD

**Comment by lucca65** [comment]
Não bro, adicionei um teste com os mesmos parâmetros e o erro não aparece. Coloquei uma captura do Sentry pra tentar entender oq tá rolando

**Comment by NeoVier** [comment]
@lucca65 fiz o deploy em staging e consegui forçar o erro de novo. Apareceu no Sentry aqui: https://sentry.io/organizations/cambiatus/issues/3506056096/. Acho que não diz muita coisa a mais 😬

**Review by NeoVier — APPROVED** [review]
🧹

**Pull request merged**
