### PR TITLE
Enhancement/add email workers

### LINKED ISSUE #263: Utilizar um sistema de workers para despacho de emails
# Story

Eu como desenvolvedor
Quero que os emails sejam despachados com workers
Para tornar mais robusto o sistema de envio de email da Cambiatus

### Descrição do Problema

Atualmente os email de transfer e claims são gerados e despachados logo em seguida, sem serem colocados em uma fila de envio. Dessa maneira, se houver uma falha no envio o email é perdido. Essa falha pode ocorrer por diversos motivos, como o limite de envio de emails pelo nosso provedor ou alguma instabilidade temporária.

Para contornar esse problema podemos elaborar um sistema de workers para despacho de todos os emails. Como referência, esse sistema já é utilizado pelos emails de digest.

### PR DESCRIPTION
**Pull request by MatheusBuss**
## What issue does this PR close
Closes #263 

## Changes Proposed ( a list of new changes introduced by this PR)
Realizar o despacho de emails de claims e transfers através de um sistema de queues e workers

### CODE REVIEW

**Comment by NeoVier** [comment]
image

I'm pretty sure it worked 🤣 I got 60+ emails

**Review by NeoVier — APPROVED** [review]
Nice and simple ✨

**Comment by MatheusBuss** [comment]
> I'm pretty sure it worked rofl I got 60+ emails

As funny as this is, it got me thinking. This will probably happen to all users with email enabled as soon as we roll this into prod :upside_down_face:

**Comment by lucca65** [comment]
Any way to avoid this @MatheusBuss? Looks a little undesirable 😀

**Comment by MatheusBuss** [comment]
I'm not entirely sure why it happened in the first place. I don't really know how this was all backlogged. I've received a single outdated email too.

I've been thinking about it and maybe it could have something to do with updating the db_listener?

Other causes could be me messing around with the db itself. I'm not convinced that these emails were sent with oban, since I recall getting oban to work after receiving my email.

Anyway, I'll keep trying to figure it out.

**Comment by lucca65** [comment]
at first I thought we would need simply clean `oban_jobs` table, but it will not work. If you need help let me know we can debug this together

**Comment by lucca65** [comment]
bro a place to investigate would be the database triggers. there is a migration that add this. Those triggers are responsible to call this db_listener.ex file

**Comment by MatheusBuss** [comment]
Just to have it written somewhere. We concluded that the mass email sending happened because the script updated some values on the db. Some of these values were transfers or claims. When these values were updated they triggered the db_listener, which is what we use to know when to send emails. Since there's no distinction between updating or creating values this change told the db_listener to dispatch emails.

**Review by lucca65 — CHANGES_REQUESTED** [review]
question, does this code make the mail queue start as paused? I think we will need to start this as paused to review if we want to shoot the emails or drop them at the time of the release

**Comment by MatheusBuss** [comment]
This does not prevent Oban from sending emails yet.

We had discussed making two other issues, one to pause the queue and other to resume it.

We could just implement this one paused to save us one issue though.

**Comment by lucca65** [comment]
+1 to merge this one as paused from the get go!

**Comment by MatheusBuss** [comment]
@lucca65 I've commented the code to put emails on the queue and created #285 to remind us to resume Oban after we roll out this PR.

**Review by lucca65 — APPROVED** [review]
Sweet! this next release is going to be full of stuff!!

**Pull request merged**
