### PR TITLE
Update the architecture workflow diagram

### PR DESCRIPTION
**Pull request by victorgdev**
Update the architecture workflow diagram

### CODE REVIEW

**Review by NeoVier — APPROVED** [review]
:rocket:

**Review by lucca65 — CHANGES_REQUESTED** [review]
@victorgdev Can we move this to our wiki: https://github.com/cambiatus/cambiatus.github.io ?

Because this is hidden (its on a hidden folder `.github`) and we have the wiki for this type of thing.

**Comment by lucca65** [comment]
but +1000 this new flow is 🔥

**Comment by victorgdev** [comment]
I will insert the diagram in the [Onboarding devs](https://cambiatus.github.io/onboarding.html) page in the Architecture section.

**Comment by lucca65** [comment]
@victorgdev I still think this information is hidden, if we want to keep it on this repo, we should remove the hidden files to a place where they are visible, like our realmente

**Comment by NeoVier** [comment]
I think most of the content in `deep-dive.md` would be better placed in the wiki, since it's related to our entire architecture, not specifically to the backend

**Comment by victorgdev** [comment]
Ok. In this PR, I will delete `deep-dive.md` file and keep the new diagram in the main `README.md` file. 

I will also create an issue on the wiki repo to add the same `deep-dive.md` content in the there.

**Pull request merged**
